# Generated by Django 2.2.10 on 2020-05-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Pz', 'Pizzas'), ('Sb', 'Subs'), ('Ps', 'Pastas'), ('Sd', 'Salads'), ('Dn', 'Dinner')], max_length=2)),
                ('name', models.CharField(max_length=80)),
                ('item_size', models.CharField(blank=True, choices=[('S', 'Small'), ('L', 'Large'), ('X', 'Extra Large')], max_length=1)),
                ('toppings_extra', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('toppings', models.ManyToManyField(blank=True, to='orders.Topping')),
            ],
        ),
    ]
